"""Initial migration with all models

Revision ID: e08bd99be194
Revises: 
Create Date: 2025-12-26 11:25:26.229801

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e08bd99be194'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('domain_reputation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=False),
    sa.Column('reputation_score', sa.Integer(), nullable=False),
    sa.Column('total_emails', sa.Integer(), nullable=False),
    sa.Column('valid_emails', sa.Integer(), nullable=False),
    sa.Column('bounced_emails', sa.Integer(), nullable=False),
    sa.Column('manual_score', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('domain_reputation', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_domain_reputation_domain'), ['domain'], unique=True)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('last_activity', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_role'), ['role'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('activity_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('resource_type', sa.String(length=50), nullable=True),
    sa.Column('resource_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('activity_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_activity_logs_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_activity_logs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_activity_logs_user_id'), ['user_id'], unique=False)

    op.create_table('batches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('total_count', sa.Integer(), nullable=False),
    sa.Column('valid_count', sa.Integer(), nullable=False),
    sa.Column('invalid_count', sa.Integer(), nullable=False),
    sa.Column('rejected_count', sa.Integer(), nullable=False),
    sa.Column('duplicate_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('tags', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('batches', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_batches_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_batches_user_id'), ['user_id'], unique=False)

    op.create_table('export_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('filter_settings', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('export_templates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_export_templates_user_id'), ['user_id'], unique=False)

    op.create_table('ignore_domains',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=False),
    sa.Column('added_by', sa.Integer(), nullable=False),
    sa.Column('added_at', sa.DateTime(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['added_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ignore_domains', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ignore_domains_domain'), ['domain'], unique=True)

    op.create_table('scheduled_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('frequency', sa.String(length=50), nullable=False),
    sa.Column('next_run', sa.DateTime(), nullable=False),
    sa.Column('report_type', sa.String(length=50), nullable=False),
    sa.Column('include_charts', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_run', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('scheduled_reports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scheduled_reports_user_id'), ['user_id'], unique=False)

    op.create_table('suppression_list',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('reason', sa.String(length=100), nullable=True),
    sa.Column('added_at', sa.DateTime(), nullable=False),
    sa.Column('added_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['added_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('suppression_list', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_suppression_list_email'), ['email'], unique=True)

    op.create_table('download_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=True),
    sa.Column('download_type', sa.String(length=50), nullable=False),
    sa.Column('filter_domains', sa.Text(), nullable=True),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('file_size', sa.BigInteger(), nullable=True),
    sa.Column('record_count', sa.Integer(), nullable=False),
    sa.Column('downloaded_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['batches.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('download_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_download_history_batch_id'), ['batch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_download_history_user_id'), ['user_id'], unique=False)

    op.create_table('emails',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=False),
    sa.Column('domain_category', sa.String(length=50), nullable=True),
    sa.Column('is_validated', sa.Boolean(), nullable=False),
    sa.Column('is_valid', sa.Boolean(), nullable=True),
    sa.Column('validation_error', sa.Text(), nullable=True),
    sa.Column('quality_score', sa.Integer(), nullable=True),
    sa.Column('batch_id', sa.Integer(), nullable=False),
    sa.Column('uploaded_by', sa.Integer(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.Column('consent_granted', sa.Boolean(), nullable=False),
    sa.Column('suppressed', sa.Boolean(), nullable=False),
    sa.Column('downloaded', sa.Boolean(), nullable=False),
    sa.Column('download_count', sa.Integer(), nullable=False),
    sa.Column('engagement_prediction', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['batch_id'], ['batches.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('emails', schema=None) as batch_op:
        batch_op.create_index('idx_batch_valid', ['batch_id', 'is_valid'], unique=False)
        batch_op.create_index('idx_email_domain', ['email', 'domain'], unique=False)
        batch_op.create_index(batch_op.f('ix_emails_batch_id'), ['batch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_emails_domain'), ['domain'], unique=False)
        batch_op.create_index(batch_op.f('ix_emails_domain_category'), ['domain_category'], unique=False)
        batch_op.create_index(batch_op.f('ix_emails_downloaded'), ['downloaded'], unique=False)
        batch_op.create_index(batch_op.f('ix_emails_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_emails_is_validated'), ['is_validated'], unique=False)
        batch_op.create_index(batch_op.f('ix_emails_suppressed'), ['suppressed'], unique=False)
        batch_op.create_index(batch_op.f('ix_emails_uploaded_by'), ['uploaded_by'], unique=False)

    op.create_table('jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.String(length=255), nullable=False),
    sa.Column('job_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('total', sa.Integer(), nullable=False),
    sa.Column('processed', sa.Integer(), nullable=False),
    sa.Column('errors', sa.Integer(), nullable=False),
    sa.Column('progress_percent', sa.Float(), nullable=False),
    sa.Column('result_message', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('result_data', sa.JSON(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['batch_id'], ['batches.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_jobs_batch_id'), ['batch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_jobs_job_id'), ['job_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_jobs_job_type'), ['job_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_jobs_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_jobs_user_id'), ['user_id'], unique=False)

    op.create_table('rejected_emails',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=False),
    sa.Column('reason', sa.String(length=100), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('batch_id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=True),
    sa.Column('rejected_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['batches.id'], ),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('rejected_emails', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rejected_emails_batch_id'), ['batch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_rejected_emails_domain'), ['domain'], unique=False)
        batch_op.create_index(batch_op.f('ix_rejected_emails_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_rejected_emails_job_id'), ['job_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_rejected_emails_reason'), ['reason'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rejected_emails', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rejected_emails_reason'))
        batch_op.drop_index(batch_op.f('ix_rejected_emails_job_id'))
        batch_op.drop_index(batch_op.f('ix_rejected_emails_email'))
        batch_op.drop_index(batch_op.f('ix_rejected_emails_domain'))
        batch_op.drop_index(batch_op.f('ix_rejected_emails_batch_id'))

    op.drop_table('rejected_emails')
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_jobs_user_id'))
        batch_op.drop_index(batch_op.f('ix_jobs_status'))
        batch_op.drop_index(batch_op.f('ix_jobs_job_type'))
        batch_op.drop_index(batch_op.f('ix_jobs_job_id'))
        batch_op.drop_index(batch_op.f('ix_jobs_batch_id'))

    op.drop_table('jobs')
    with op.batch_alter_table('emails', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_emails_uploaded_by'))
        batch_op.drop_index(batch_op.f('ix_emails_suppressed'))
        batch_op.drop_index(batch_op.f('ix_emails_is_validated'))
        batch_op.drop_index(batch_op.f('ix_emails_email'))
        batch_op.drop_index(batch_op.f('ix_emails_downloaded'))
        batch_op.drop_index(batch_op.f('ix_emails_domain_category'))
        batch_op.drop_index(batch_op.f('ix_emails_domain'))
        batch_op.drop_index(batch_op.f('ix_emails_batch_id'))
        batch_op.drop_index('idx_email_domain')
        batch_op.drop_index('idx_batch_valid')

    op.drop_table('emails')
    with op.batch_alter_table('download_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_download_history_user_id'))
        batch_op.drop_index(batch_op.f('ix_download_history_batch_id'))

    op.drop_table('download_history')
    with op.batch_alter_table('suppression_list', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_suppression_list_email'))

    op.drop_table('suppression_list')
    with op.batch_alter_table('scheduled_reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scheduled_reports_user_id'))

    op.drop_table('scheduled_reports')
    with op.batch_alter_table('ignore_domains', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ignore_domains_domain'))

    op.drop_table('ignore_domains')
    with op.batch_alter_table('export_templates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_export_templates_user_id'))

    op.drop_table('export_templates')
    with op.batch_alter_table('batches', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_batches_user_id'))
        batch_op.drop_index(batch_op.f('ix_batches_status'))

    op.drop_table('batches')
    with op.batch_alter_table('activity_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_activity_logs_user_id'))
        batch_op.drop_index(batch_op.f('ix_activity_logs_created_at'))
        batch_op.drop_index(batch_op.f('ix_activity_logs_action'))

    op.drop_table('activity_logs')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_role'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('domain_reputation', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_domain_reputation_domain'))

    op.drop_table('domain_reputation')
    # ### end Alembic commands ###
